/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Orklas
 * This is an api spec for room reservation program.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

